#ifndef PEMUTIL_OVERFLOW_H_
#define PEMUTIL_OVERFLOW_H_

#include <stdbool.h>
#include <stdint.h>
#include <stddef.h>
#include <signal.h>
#include <wchar.h>

/* This file is autogenerated by pemutils/scripts/overflow_gen.py
 * All edits will be deleted. */

bool add_overflow_schar(signed char x, signed char y);
bool add_overflow_uchar(unsigned char x, unsigned char y);
bool add_overflow_shrt(short x, short y);
bool add_overflow_ushrt(unsigned short x, unsigned short y);
bool add_overflow_int(int x, int y);
bool add_overflow_uint(unsigned int x, unsigned int y);
bool add_overflow_long(long x, long y);
bool add_overflow_ulong(unsigned long x, unsigned long y);
bool add_overflow_llong(long long x, long long y);
bool add_overflow_ullong(unsigned long long x, unsigned long long y);
bool add_overflow_size(size_t x, size_t y);
bool add_overflow_intmax(intmax_t x, intmax_t y);
bool add_overflow_uintmax(uintmax_t x, uintmax_t y);
bool add_overflow_intptr(intptr_t x, intptr_t y);
bool add_overflow_uintptr(uintptr_t x, uintptr_t y);
bool add_overflow_wchar(wchar_t x, wchar_t y);
bool add_overflow_wint(wint_t x, wint_t y);
bool add_overflow_sig_atomic(sig_atomic_t x, sig_atomic_t y);
bool add_overflow_int8(int8_t x, int8_t y);
bool add_overflow_uint8(uint8_t x, uint8_t y);
bool add_overflow_int_fast8(int_fast8_t x, int_fast8_t y);
bool add_overflow_uint_fast8(uint_fast8_t x, uint_fast8_t y);
bool add_overflow_int_least8(int_least8_t x, int_least8_t y);
bool add_overflow_uint_least8(uint_least8_t x, uint_least8_t y);
bool add_overflow_int16(int16_t x, int16_t y);
bool add_overflow_uint16(uint16_t x, uint16_t y);
bool add_overflow_int_fast16(int_fast16_t x, int_fast16_t y);
bool add_overflow_uint_fast16(uint_fast16_t x, uint_fast16_t y);
bool add_overflow_int_least16(int_least16_t x, int_least16_t y);
bool add_overflow_uint_least16(uint_least16_t x, uint_least16_t y);
bool add_overflow_int32(int32_t x, int32_t y);
bool add_overflow_uint32(uint32_t x, uint32_t y);
bool add_overflow_int_fast32(int_fast32_t x, int_fast32_t y);
bool add_overflow_uint_fast32(uint_fast32_t x, uint_fast32_t y);
bool add_overflow_int_least32(int_least32_t x, int_least32_t y);
bool add_overflow_uint_least32(uint_least32_t x, uint_least32_t y);
bool add_overflow_int64(int64_t x, int64_t y);
bool add_overflow_uint64(uint64_t x, uint64_t y);
bool add_overflow_int_fast64(int_fast64_t x, int_fast64_t y);
bool add_overflow_uint_fast64(uint_fast64_t x, uint_fast64_t y);
bool add_overflow_int_least64(int_least64_t x, int_least64_t y);
bool add_overflow_uint_least64(uint_least64_t x, uint_least64_t y);

bool mult_overflow_schar(signed char x, signed char y);
bool mult_overflow_uchar(unsigned char x, unsigned char y);
bool mult_overflow_shrt(short x, short y);
bool mult_overflow_ushrt(unsigned short x, unsigned short y);
bool mult_overflow_int(int x, int y);
bool mult_overflow_uint(unsigned int x, unsigned int y);
bool mult_overflow_long(long x, long y);
bool mult_overflow_ulong(unsigned long x, unsigned long y);
bool mult_overflow_llong(long long x, long long y);
bool mult_overflow_ullong(unsigned long long x, unsigned long long y);
bool mult_overflow_size(size_t x, size_t y);
bool mult_overflow_intmax(intmax_t x, intmax_t y);
bool mult_overflow_uintmax(uintmax_t x, uintmax_t y);
bool mult_overflow_intptr(intptr_t x, intptr_t y);
bool mult_overflow_uintptr(uintptr_t x, uintptr_t y);
bool mult_overflow_wchar(wchar_t x, wchar_t y);
bool mult_overflow_wint(wint_t x, wint_t y);
bool mult_overflow_sig_atomic(sig_atomic_t x, sig_atomic_t y);
bool mult_overflow_int8(int8_t x, int8_t y);
bool mult_overflow_uint8(uint8_t x, uint8_t y);
bool mult_overflow_int_fast8(int_fast8_t x, int_fast8_t y);
bool mult_overflow_uint_fast8(uint_fast8_t x, uint_fast8_t y);
bool mult_overflow_int_least8(int_least8_t x, int_least8_t y);
bool mult_overflow_uint_least8(uint_least8_t x, uint_least8_t y);
bool mult_overflow_int16(int16_t x, int16_t y);
bool mult_overflow_uint16(uint16_t x, uint16_t y);
bool mult_overflow_int_fast16(int_fast16_t x, int_fast16_t y);
bool mult_overflow_uint_fast16(uint_fast16_t x, uint_fast16_t y);
bool mult_overflow_int_least16(int_least16_t x, int_least16_t y);
bool mult_overflow_uint_least16(uint_least16_t x, uint_least16_t y);
bool mult_overflow_int32(int32_t x, int32_t y);
bool mult_overflow_uint32(uint32_t x, uint32_t y);
bool mult_overflow_int_fast32(int_fast32_t x, int_fast32_t y);
bool mult_overflow_uint_fast32(uint_fast32_t x, uint_fast32_t y);
bool mult_overflow_int_least32(int_least32_t x, int_least32_t y);
bool mult_overflow_uint_least32(uint_least32_t x, uint_least32_t y);
bool mult_overflow_int64(int64_t x, int64_t y);
bool mult_overflow_uint64(uint64_t x, uint64_t y);
bool mult_overflow_int_fast64(int_fast64_t x, int_fast64_t y);
bool mult_overflow_uint_fast64(uint_fast64_t x, uint_fast64_t y);
bool mult_overflow_int_least64(int_least64_t x, int_least64_t y);
bool mult_overflow_uint_least64(uint_least64_t x, uint_least64_t y);

#endif /* PEMUTIL_OVERFLOW_H_ */