#include "overflow.h"
#include <limits.h>
#include <stddef.h>
#include <stdint.h>

/* This file is autogenerated by pemutils/scripts/overflow_gen.py
 * All edits will be deleted. */

bool add_overflow_int8(int8_t x, int8_t y) {
    if ((x <= 0 && y >= 0) || (x >= 0 && y <= 0)) {
        return false;
    } else if (x > 0) {
        return x > INT8_MAX - y;
    } else {
        return x < INT8_MIN - y;
    }
}

bool add_overflow_int16(int16_t x, int16_t y) {
    if ((x <= 0 && y >= 0) || (x >= 0 && y <= 0)) {
        return false;
    } else if (x > 0) {
        return x > INT16_MAX - y;
    } else {
        return x < INT16_MIN - y;
    }
}

bool add_overflow_int32(int32_t x, int32_t y) {
    if ((x <= 0 && y >= 0) || (x >= 0 && y <= 0)) {
        return false;
    } else if (x > 0) {
        return x > INT32_MAX - y;
    } else {
        return x < INT32_MIN - y;
    }
}

bool add_overflow_int64(int64_t x, int64_t y) {
    if ((x <= 0 && y >= 0) || (x >= 0 && y <= 0)) {
        return false;
    } else if (x > 0) {
        return x > INT64_MAX - y;
    } else {
        return x < INT64_MIN - y;
    }
}

bool add_overflow_uint8(uint8_t x, uint8_t y) {
    return x > UINT8_MAX - y;
}

bool add_overflow_uint16(uint16_t x, uint16_t y) {
    return x > UINT16_MAX - y;
}

bool add_overflow_uint32(uint32_t x, uint32_t y) {
    return x > UINT32_MAX - y;
}

bool add_overflow_uint64(uint64_t x, uint64_t y) {
    return x > UINT64_MAX - y;
}

bool add_overflow_schar(signed char x, signed char y) {
    if ((x <= 0 && y >= 0) || (x >= 0 && y <= 0)) {
        return false;
    } else if (x > 0) {
        return x > SCHAR_MAX - y;
    } else {
        return x < SCHAR_MIN - y;
    }
}

bool add_overflow_uchar(unsigned char x, unsigned char y) {
    return x > UCHAR_MAX - y;
}

bool add_overflow_shrt(short x, short y) {
    if ((x <= 0 && y >= 0) || (x >= 0 && y <= 0)) {
        return false;
    } else if (x > 0) {
        return x > SHRT_MAX - y;
    } else {
        return x < SHRT_MIN - y;
    }
}

bool add_overflow_ushrt(unsigned short x, unsigned short y) {
    return x > USHRT_MAX - y;
}

bool add_overflow_int(int x, int y) {
    if ((x <= 0 && y >= 0) || (x >= 0 && y <= 0)) {
        return false;
    } else if (x > 0) {
        return x > INT_MAX - y;
    } else {
        return x < INT_MIN - y;
    }
}

bool add_overflow_uint(unsigned int x, unsigned int y) {
    return x > UINT_MAX - y;
}

bool add_overflow_long(long x, long y) {
    if ((x <= 0 && y >= 0) || (x >= 0 && y <= 0)) {
        return false;
    } else if (x > 0) {
        return x > LONG_MAX - y;
    } else {
        return x < LONG_MIN - y;
    }
}

bool add_overflow_ulong(unsigned long x, unsigned long y) {
    return x > ULONG_MAX - y;
}

bool add_overflow_llong(long long x, long long y) {
    if ((x <= 0 && y >= 0) || (x >= 0 && y <= 0)) {
        return false;
    } else if (x > 0) {
        return x > LLONG_MAX - y;
    } else {
        return x < LLONG_MIN - y;
    }
}

bool add_overflow_ullong(unsigned long long x, unsigned long long y) {
    return x > ULLONG_MAX - y;
}

bool add_overflow_size(size_t x, size_t y) {
    return x > SIZE_MAX - y;
}