#ifndef PEMUTIL_OVERFLOW_H_
#define PEMUTIL_OVERFLOW_H_

#include <stdbool.h>
#include <stdint.h>
#include <stddef.h>

/* This file is autogenerated by pemutils/scripts/overflow_gen.py
 * All edits will be deleted. */

bool add_overflow_int8(int8_t x, int8_t y);
bool add_overflow_int16(int16_t x, int16_t y);
bool add_overflow_int32(int32_t x, int32_t y);
bool add_overflow_int64(int64_t x, int64_t y);
bool add_overflow_uint8(uint8_t x, uint8_t y);
bool add_overflow_uint16(uint16_t x, uint16_t y);
bool add_overflow_uint32(uint32_t x, uint32_t y);
bool add_overflow_uint64(uint64_t x, uint64_t y);
bool add_overflow_schar(signed char x, signed char y);
bool add_overflow_uchar(unsigned char x, unsigned char y);
bool add_overflow_shrt(short x, short y);
bool add_overflow_ushrt(unsigned short x, unsigned short y);
bool add_overflow_int(int x, int y);
bool add_overflow_uint(unsigned int x, unsigned int y);
bool add_overflow_long(long x, long y);
bool add_overflow_ulong(unsigned long x, unsigned long y);
bool add_overflow_llong(long long x, long long y);
bool add_overflow_ullong(unsigned long long x, unsigned long long y);
bool add_overflow_size(size_t x, size_t y);

#endif /* PEMUTIL_OVERFLOW_H_ */